services:
  mysql-radio:
    container_name: mysql-radio
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: cowradio
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: sparklecow
    ports:
      - 3306:3306
