services:
  mysql-radio:
    container_name: mysql-radio
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: cowradio
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: sparklecow
    ports:
      - 3306:3306
    networks:
      - cowradio-network
    volumes:
      - cowdata:/var/lib/mysql

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - cowradio-network

networks:
  cowradio-network:
    driver: bridge

volumes:
  cowdata:
    driver: local