server:
  port: 8080

spring:
  application:
    name: cowradio
    security:
      jwt:
        secret: 50a9c2491945272656e05eccdd90cd7242b16e24e16c3b6bbb158b77c1fc0c9b
        expiration: 86400000

  datasource:
    url: jdbc:mysql://localhost:3306/cowradio
    username: sparklecow
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


